language: node_js

env:
  - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - g++-4.9
      - mongodb-org-server
      - mongodb-org-shell

node_js:
  - "stable"

notifications:
  email:
    on_success: never
    on_failure: never

before_script:
  - sleep 5

script:
  - npm test