language: node_js

env:
  - CXX=g++-4.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

services:
  - mongodb

node_js:
  - "stable"

notifications:
  slack:
    on_success: never
    on_failure: never
  email:
    on_success: never
    on_failure: never

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
  - npm install

script:
  - npm test